apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
spec:
  containers:
  - name: registry
    image: //tools/registry:image
    volumeMounts:
    # - name: repo-vol
    #   mountPath: "/var/lib/registry"
    - name: certs-vol
      mountPath: "/certs"
      readOnly: true
    env:
    - name: REGISTRY_HTTP_TLS_CERTIFICATE
      value: "/certs/tls.crt"
    - name: REGISTRY_HTTP_TLS_KEY
      value: "/certs/tls.key"
  volumes:
  # - name: repo-vol
  #   persistentVolumeClaim:
  #     claimName: registry-pvc
  - name: certs-vol
    secret:
      secretName: registry
      items:
      - key: registry_cert.key
        path: tls.key
      - key: registry_cert.crt
        path: tls.crt
