[package]
name = "mono-repo-rust-3rdparty"
version = "0.1.0"
edition = "2021"

[lib]
path = "fake_lib.rs"

[dependencies]
clap = { version = "4.0.17", features = [ "default" , "derive", "env" ] }
env_logger = "0.9.1"
grpc = "0.8.3"
log = "0.4.17"

[package.metadata.raze]
workspace_path = "//third-party/rust/cargo"
package_aliases_dir = "."
default_gen_buildrs = true
targets = [
    "aarch64-apple-darwin",
]
genmode = "Remote"

[package.metadata.raze.crates.clap.'*']
compile_data_attr = "glob([\"**/*.md\"])"

[package.metadata.raze.crates.clap_derive.'*']
compile_data_attr = "glob([\"**/*.md\"])"
