apiVersion: apps/v1
kind: Deployment
metadata:
  name: detail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detail
  template:
    metadata:
      labels:
        app: detail
    spec:
      containers:
        - name: detail
          image: services/detail:latest
          args:
            - --port=50050
          ports:
            - containerPort: 50050
              name: grpc
          resources:
            requests:
              memory: 100Mi
          # livenessProbe:
          #   grpc:
          #     port: 50050
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - "NET_ADMIN"
