apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        app_label_image_short_digest: "{{//services/product/cmd/server:image.short-digest}}"
      annotations:
        inject.istio.io/templates: grpc-agent
        proxy.istio.io/config: |
          {"holdApplicationUntilProxyStarts": true}
    spec:
      containers:
        - name: product
          image: //services/product/cmd/server:image
          args:
            - --port=50050
          ports:
            - containerPort: 50050
              name: grpc
            - containerPort: 8080
              name: http
          resources:
            requests:
              memory: 100Mi
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - "NET_ADMIN"
