apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: product
          image: services/product:latest
          args:
            - --port=50050
            - --logtostderr
          ports:
            - containerPort: 50050
              name: grpc
          resources:
            requests:
              memory: 100Mi
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: GRPC_GO_LOG_VERBOSITY_LEVEL
              value: "trace"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - "NET_ADMIN"
