apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  ports:
    - protocol: TCP
      port: 50050
      targetPort: grpc
      name: grpc
    - protocol: TCP
      port: 8080
      targetPort: http
      name: http
